---
- name: Install packages
  apt: name={{item}} state=present update-cache=yes cache_valid_time=864000
  become: yes
  with_items:
    - sudo
    - man
    - vim
    - nano
    - mc
    - curl
    - wget
    - htop
    - tzdata
    - apt-transport-https
    - ca-certificates
    - python-software-properties
    - software-properties-common
